{{- if not .Values.apiToken.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptime-private-location.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uptime-private-location.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "uptime-private-location.secretKey" . }}: {{ required "apiToken.value is required when apiToken.secretName is not set" .Values.apiToken.value | quote }}
{{- end }}
