{{- if eq .Values.kind "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "uptime-private-location.fullname" . }}
  labels:
    {{- include "uptime-private-location.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "uptime-private-location.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "uptime-private-location.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "uptime-private-location.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "uptime-private-location.podSpec" . | nindent 6 }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: nagios-var
      spec:
        accessModes: {{ toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.nagiosVar.size }}
    - metadata:
        name: uptime-var
      spec:
        accessModes: {{ toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.uptimeVar.size }}
    - metadata:
        name: uptime-logs
      spec:
        accessModes: {{ toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.uptimeLogs.size }}
  {{- end }}
{{- end }}
